# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc32210eadcd1bc67e1b22859118ba1d71b3ba9352f2472a82258d1383d2ad44cf56a98e53f7ba153cffa8faa9ea4bc597081fc70cebdd11f56ddbb30959fdc0

test:
  secret_key_base: d2da3123bcfe305c5ed86eda5f54c2466c2c151e903664362f86921fddca4071dce3daaf62f0f86c40046fdbb20f23e5493de2535774f3cc333900a3ce3fe088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
